<?php

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \AHT\Salesagents\Block\Customer\Salesagents $block */

$productcollection = $block->getProductCollection();
$formatCurrency = $this->helper('Magento\Framework\Pricing\Helper\Data');

?>

<?php if ($productcollection) : ?>
    <?php $productcollection_number = count($productcollection);
    if ($productcollection_number > 0) : ?>
        <div class="table-wrapper sa-products">
            <table class="data table" id="my-sa-product-table">
                <caption class="table-caption"><?= $block->escapeHtml(__('SA Products')) ?></caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id"><?= $block->escapeHtml(__('Product Name')) ?></th>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('SKU')) ?></th>
                        <th scope="col" class="col date"><?= $block->escapeHtml(__('Price')) ?></th>
                        <?= $block->getChildHtml('extra.column.header') ?>
                        <th scope="col" class="col total"><?= $block->escapeHtml(__('Commisson Type')) ?></th>
                        <th scope="col" class="col status"><?= $block->escapeHtml(__('Commission Value')) ?></th>
                        <th scope="col" class="col total"><?= $block->escapeHtml(__('Commisson Result')) ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($productcollection as $products) : ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col id"><a href="<?= $products->getProductUrl()  ?>"><?= $block->escapeHtml($products->getName()) ?></a></td>
                            <td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col date"><?= /* @noEscape */ $block->escapeHtml($products->getSku()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col date"><?= /* @noEscape */ $formatCurrency->currency($products->getPrice()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Commisson Type')) ?>" class="col total">
                                <?php $typeCommisson = $products->getCommissionType();
                                if ($typeCommisson == 1) {
                                    echo 'Fixed';
                                } else {
                                    echo 'Percent';
                                }
                                ?></td>
                            <?php /* @noEscape */ $typeCommisson = $products->getCommissionType();
                            if ($typeCommisson == 1) : ?>
                                <td data-th="<?= $block->escapeHtml(__('Commission Value')) ?>" class="col status">$<?= number_format(($products->getCommissionValue()), 2, ".", ",")  ?></td>
                            <?php else :    ?>
                                <td data-th="<?= $block->escapeHtml(__('Commission Result')) ?>" class="col status"><?= number_format(($products->getCommissionValue()), 2, ".", ",")  ?> %</td>
                            <?php endif ?></td>
                            <?php /* @noEscape */ $typeCommisson = $products->getCommissionType();
                            if ($typeCommisson == 1) : ?>
                                <td data-th="<?= $block->escapeHtml(__('Commission Result')) ?>" class="col status"><?= $formatCurrency->currency($products->getCommissionValue(), true, false)  ?></td>
                            <?php else :    ?>
                                <td data-th="<?= $block->escapeHtml(__('Commission Result')) ?>" class="col status"><?= $formatCurrency->currency(($products->getCommissionValue() * $products->getPrice() / 100), true, false)  ?></td>
                            <?php endif ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <?php if ($block->getPagerHtml()) : ?>
            <div class="SA-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
    <?php else : ?>
        <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyProductMessage()) ?></span></div>
    <?php endif ?>
<?php endif ?>